Fix portlet assignment mapping import, so that it has acquisition support.
The mapping from plone.app.portlets needs to be used, not from plone.portlets.
Otherwise it will result in an error when exporting with generic setup:

    AttributeError: 'PortletAssignmentMapping' object has no attribute '__of__'